# Generated by Django 3.2.6 on 2024-04-12 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='isConfirmed',
            field=models.BooleanField(default=False),
        ),
    ]
